# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Source Options
use_modern_java_syntax = false
use_jetbrains_annotations = false

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = true
show_testing_output = false

# Mod Information
mod_version = 2.8.4
root_package = com.direwolf20.buildinggadgets
mod_id = buildinggadgets
mod_name = Building Gadgets Unofficial

# Mod Metadata
mod_description = Adds some gadgets to help you build!
mod_url = https://minecraft.curseforge.com/projects/building-gadgets
mod_update_json = https://github.com/Direwolf20-MC/BuildingGadgets/raw/master/update.json
mod_authors = Direwolf20
mod_credits = The Forge and FML guys, McJty, Vazkii, CPW, and Pahimar for helping me learn java/forge modding. Rorax for the textures!
mod_logo_path = assets/buildinggadgets/textures/logo/logo.png

# Mapping Properties
mapping_channel = stable
mapping_version = 39
use_dependency_at_files = true

# Run Configurations
minecraft_username = XSmallWhiteX
extra_jvm_args =
extra_tweak_classes =

# Maven Publishing
publish_to_maven = false
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =

# Publishing
release_type = release
publish_with_changelog = ${{ it.file('CHANGELOG.md').exists() }}

# Publishing to CurseForge
publish_to_curseforge = false
curseforge_project_id =
curseforge_debug = false

# Publishing to Modrinth
publish_to_modrinth = false
modrinth_project_id =
modrinth_sync_readme = false
modrinth_debug = false

# Modify Minecraft Sources
change_minecraft_sources = false

# Tags
use_tags = true
tag_class_name = ${root_package}.common.Tags

# Access Transformers
use_access_transformer = false
access_transformer_locations = ${mod_id}_at.cfg

# Mixins
use_mixins = false
mixin_booter_version = 10.7
generate_mixins_json = true
mixin_configs = ${mod_id}
mixin_refmap = mixins.${mod_id}.refmap.json
mixin_package =

# Coremods
is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name =

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5
